### ISSUE TITLE
All tests just pass

### ISSUE THREAD

**Issue by lukebuehler** [zonca/pytest-ipynb#15] opened 2016-01-22 14:55 UTC
I'm having troubles getting this to work with the latest jupyter amd IPython version (4.1, 4.0 respectively). All test just simply pass although I have asserts that should definitely fail. Am I missing something?

Let's say I have following two cells:

    """setup"""
    print('setting up stome stuff')
    a = "something you might need"

And

    """test_five"""
    assert 1 < 0, "serious problems"

I just get this output
============================= test session starts =============================
platform win32 -- Python 3.4.4, pytest-2.8.5, py-1.4.31, pluggy-0.3.1 -- C:\Program Files\Anaconda3\envs\attribution\python.exe
cachedir: .cache
rootdir: F:\ASC Team Project\MAIN\ASC.IPG\TA\ReturnAttributionQA\attribution_tests, inifile:
plugins: ipynb-1.0.2
collected 2 items 

test_ha.ipynb::test_ha.ipynb::cell 1, setup PASSED
test_ha.ipynb::test_ha.ipynb::cell 2, test five PASSED

========================== 2 passed in 5.10 seconds ===========================

**Comment by zonca** [comment] 2016-01-23 05:32
untested with the last IPython! I'll take a look next week

**Comment by lukebuehler** [comment] 2016-01-23 18:12
thank you!

**Comment by michaelaye** [comment] 2016-02-03 20:21
For what it's worth, I'm using notebook 5.0.0.dev and IPython 4.1.1 and I get failed tests:
```bash
plugins: ipynb-1.0.2
collected 3 items

test_crap.ipynb::notebooks/tests/test_crap.ipynb::cell 1, setup PASSED
test_crap.ipynb::notebooks/tests/test_crap.ipynb::cell 2, test five FAILED
test_crap.ipynb::notebooks/tests/test_crap.ipynb::cell 3, no description PASSED

======================================================= FAILURES =======================================================
___________________________________________________________  ___________________________________________________________
Notebook execution failed
Cell 2: test five

Input:
"""test_five"""
assert 1 < 0, "serious problems"

Traceback:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-5e9eccf10dc6> in <module>()
      1 """test_five"""
----> 2 assert 1 < 0, "serious problems"

AssertionError: serious problems

========================================== 1 failed, 2 passed in 6.07 seconds ==========================================
```

**Comment by zonca** [comment] 2016-02-18 18:06
tested with IPython 4.1 and notebook 4.1, cannot reproduce this, closing issue.

@lukebuehler please reopen with more details if you still have this issue

**Closed by zonca** 2016-02-18 18:06 UTC

**Comment by lukebuehler** [comment] 2016-02-18 19:56
I will take a look again and see if I can get it to work. I did think it was a bug, but if its not reproducible it's probably on my side.

**Comment by filip-z** [comment] 2016-08-24 13:44
I am experiencing the same issue that all tests just pass.  Even in the example notebook which has the last test set-up to fail, everything passes.

I am running the latest version of Anaconda (conda 4.1.11) on Windows.
